### PR TITLE
add external api test script for validating fetch api 

### PR DESCRIPTION
**Pull request by relud**
(and other stuff eventually)

r? @oyiptong

### CODE REVIEW

**Comment by relud** [comment]
the script works against prod, but against stage it complains about the absence of locales. @oyiptong how does the client handle fetching w/ locale? does it send a locale, if that works great, if it returns 204, check without locale?

**Comment by relud** [comment]
now the build failure isn't related to me

**Comment by oyiptong** [comment]
The build failure is due to a change in the build env in Travis.

Will take a look

**Comment by oyiptong** [comment]
build should be fixed. once you merge master into your branch, travis should do as expected

**Comment by oyiptong** [comment]
using gevent with requests would yield better performance. as it stands, the files are being requested sequentially.

I suggest checking out grequests: https://github.com/kennethreitz/grequests

**Comment by relud** [comment]
grequests support added

**Comment by relud** [comment]
method removed

**Comment by relud** [comment]
updating this to include the v3 endpoint stuff

**Comment by karlht** [comment]
r+, in the case that that CI comes back green.

**Comment by oyiptong** [comment]
r+

**Pull request closed without merging**
